# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ekle.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets
import os 


class Ui_EklePage(object):
    def setupUi(self, EklePage):
        EklePage.setObjectName("EklePage")
        EklePage.resize(330, 277)
        self.centralwidget = QtWidgets.QWidget(EklePage)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(70, 100, 181, 81))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.splitter = QtWidgets.QSplitter(self.layoutWidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout.addWidget(self.lineEdit_2)
        self.gridLayout.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.splitter, 0, 0, 1, 1)
        self.addButton = QtWidgets.QPushButton(self.layoutWidget)
        self.addButton.setObjectName("addButton")
        self.addButton.clicked.connect(self.addButton_Clicked)
        self.gridLayout_2.addWidget(self.addButton, 1, 0, 1, 1)
      
        EklePage.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(EklePage)
        self.statusbar.setObjectName("statusbar")
        EklePage.setStatusBar(self.statusbar)

        self.retranslateUi(EklePage)
        QtCore.QMetaObject.connectSlotsByName(EklePage)
  



     

    def addButton_Clicked(self,EklePage):
        
        with open("anlamlar.txt", "a") as myfile:
            myfile.write('\n'+self.lineEdit_2.text())
            
        with open("kelimeler.txt", "a") as myfile:
            myfile.write('\n'+self.lineEdit.text())
                    
                    
        


    def retranslateUi(self, EklePage):
        _translate = QtCore.QCoreApplication.translate
        EklePage.setWindowTitle(_translate("EklePage", "MainWindow"))
        self.label.setText(_translate("EklePage", "kelime:"))
        self.label_2.setText(_translate("EklePage", "anlamı:"))
        self.addButton.setText(_translate("EklePage", "ekle"))
        


    

if __name__ == "__main__":

 
    app = QtWidgets.QApplication(sys.argv)
    EklePage = QtWidgets.QMainWindow()
    ui = Ui_EklePage()
    ui.setupUi(EklePage)
    EklePage.show()
    sys.exit(app.exec_())
